<?php

/**
 * Implements hook_autoload_info().
 */
function site_alert_autoload_info() {
  return array(
    'BlockSiteAlert' => 'includes/block.site_alert.inc',
  );
}

/**
 * Prepares variables for site alert blocks.
 */
function site_alert_preprocess_block(&$variables) {
  $block = $variables['block'];
  if (get_class($block) == 'BlockSiteAlert') {
    if (isset($block->settings['sitealert'])) {
      $variables['classes'][] = 'block-site-alert';
    }
  }
  }

/**
 * Implements hook_block_info().
 */
function site_alert_block_info() {
  $blocks = array();
  $default_info = t('Add different color alert messages in a block.');
  $blocks['default'] = array(
    // The name that will appear in the block list.
    'info' => t('Site Alert Block'),
    'description' => $default_info,
    'class' => 'BlockSiteAlert',
  );
  return $blocks;
}




